### ISSUE TITLE
feature roadmap

### ISSUE THREAD

**Issue by will0** [will0/esp#1]
need to finalize the initial feature roapmap

**Comment by will0** [comment]
- [ ] improved password hashing via password_hash
- [ ] audit logging

**Comment by will0** [comment]
- [ ] various MFA

**Comment by will0** [comment]
- [ ] various rate limits

**Comment by will0** [comment]
- [ ] telemetry
- [ ] filesystem content signature tracking

**Comment by will0** [comment]
- [ ] wpvulndb integration

**Comment by will0** [comment]
- [ ] CSP reporting

**Comment by will0** [comment]
moved to https://github.com/will0/esp/projects/1
